version: '3'
services:
  bdapi-auth:
    build:
      context: .
      dockerfile: Dockerfile-dev
    volumes:
      - './:/app'
    links:
      - db
    ports:
      - "5202:80"
    environment:
      - ENV=dev
  db:
    image: neo4j
    ports:
      - "7474:7474"
      - "7473:7473"
      - "7687:7687"
