---
apiVersion: v1
kind: Service
metadata:
  name: bdapi-kits
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v1
      kind:  Mapping
      name:  bdapi-kits_mapping
      prefix: /kit/
      rewrite: /kit/
      service: bdapi-kits
spec:
  selector:
    app: bdapi-kits
  ports:
  - port: 80
    name: http-bdapi-kits
    targetPort: http-api
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: bdapi-kits
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: bdapi-kits
    spec:
      containers:
      - name: bdapi-kits
        image: buildarium/bdapi-kits:latest
        imagePullPolicy: "Always"
        env:
        - name: ENV
          value: "prod"
        - name: DBUSER
          valueFrom:
            secretKeyRef:
              name: bdapi-secret
              key: neouser
        - name: DBPASS
          valueFrom:
            secretKeyRef:
              name: bdapi-secret
              key: neopass
        ports:
        - name: http-api
          containerPort: 80
        # readinessProbe:
        #   httpGet:
        #     path: /health
        #     port: 5000
        #   initialDelaySeconds: 30
        #   periodSeconds: 3
        # resources:
        #   limits:
        #     cpu: "0.1"
        #     memory: 100Mi
